CREATE TABLE `articolo` (
                            `id` varchar(80) NOT NULL,
                            `id_richiesta` varchar(80) NOT NULL,
                            `processed` tinyint(1) DEFAULT '0' COMMENT '0 = false, 1 = true',
                            `alias_astenpos` varchar(150) DEFAULT '' COMMENT 'astenpos',
                            `alias_stelle` varchar(150) DEFAULT '' COMMENT '5stelle',
                            `art_description` varchar(150) DEFAULT '',
                            `cat_description` varchar(150) DEFAULT '',
                            `um` varchar(2) DEFAULT 'PZ' COMMENT 'mexal unità di misura max 2',
                            `type` varchar(1) DEFAULT 'M' COMMENT 'mexal tipo art default ''M''',
                            `net_price_1` float(7,2) DEFAULT '0.00',
                            `net_price_2` float(7,2) DEFAULT '0.00',
                            `net_price_3` float(7,2) DEFAULT '0.00',
                            `net_price_4` float(7,2) DEFAULT '0.00',
                            `net_price_5` float(7,2) DEFAULT '0.00',
                            `net_price_6` float(7,2) DEFAULT '0.00',
                            `net_price_7` float(7,2) DEFAULT '0.00',
                            `net_price_8` float(7,2) DEFAULT '0.00',
                            `net_price_9` float(7,2) DEFAULT '0.00',
                            `cost` float(7,2) DEFAULT '0.00',
                            `vat` int(11) DEFAULT '0',
                            `vat_nature` varchar(50) DEFAULT '',
                            `alias_1` varchar(150) DEFAULT '' COMMENT 'other',
                            PRIMARY KEY (`id`,`id_richiesta`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=latin1 ROW_FORMAT=COMPACT;